site_name: Techexcel BackOffice Doc
site_description: Enhanced documentation for Lucee CFML Engine
site_url: https://chapkepratham007.github.io/mkdocs1/
repo_url: https://github.com/chapkepratham007/mkdocs1

theme:
  name: material
  palette:
    - scheme: default
      primary: light blue
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: light blue
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - tables
  - def_list

plugins:
  - search

nav:
  - Home: index.md
  - Getting Started:
    - First Steps:
      - Quick Start: getting-started/first-steps/quick-start.md
      - Installation: getting-started/first-steps/installation.md
      - Configuration: getting-started/first-steps/configuration.md
    - Requirements:
      - Hardware: getting-started/system-requirements/hardware.md
      - Software: getting-started/system-requirements/software.md
    - Reference Tables:
      - Operators: syntax/reference/operators.md
      - Functions: syntax/reference/functions.md

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js
